### ISSUE TITLE
Codeml (v 4v4d) using fixed kappa value, reports wrong kappa

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-run#35]
---

Author Name: **Janet Young** (Janet Young)
Original Redmine Issue: 3331, https://redmine.open-bio.org/issues/3331
Original Date: 2012-03-06
Original Assignee: Bioperl Guts

---

Hi there,

After a long absence, I’ve started using Bioperl to run PAML again. Apologies if I’m bringing up another one of those annoying “PAML changed and broke the parser” kinds of issues… Is PAML v4.4d supported?

I found a minor bug/issue I thought you might want to know about: if I set up a ka_ks_factory and specify fix_kappa = 1, then I recover the kappa via get_MLmatrix, it actually reports to me the omega (not the kappa). I’ll attach a script that shows this (I’ll include output as comments in the script). I think the example script should explain everything, but please let me know if you need more details…

thanks very much,

Janet Young

---

Dr. Janet Young

Tapscott and Malik labs

Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., C3-168,
P.O. Box 19024, Seattle, WA 98109-1024, USA.

email: jayoung …at… fhcrc.org

---

**Comment by cjfields** [comment]
---

Original Redmine Comment
Author Name: **Jason Stajich** 
Original Date: 2012-03-13T16:53:53Z

---

You are definitely the first to use/report on 4.4d… hopefully someone can look at it quickly as it sounds like a quick fix.

**Comment by cjfields** [comment]
---

Original Redmine Comment
Author Name: **Daisie Huang** 
Original Date: 2012-06-20T23:02:49Z

---

Fixed at https://github.com/daisieh/bioperl-live/zipball/bug3331

**Comment by carandraug** [comment]
Fixed and merged into bioperl-live with bioperl/bioperl-live@f7b9e38b1060738f9b
