### ISSUE TITLE
Bio::Tools::Run::StandAloneBlastPlus HTML output

### ISSUE THREAD

**Issue by bretonics** [bioperl/bioperl-run#48]
How can we get an html output?

I have tried several things but it either outputs in html format (with errors) or regular format. This is how it looks:

**No HTML Output**
```
# Create StandAloneBlastPlus Factory
        my $fac = Bio::Tools::Run::StandAloneBlastPlus->new(
                    -db_data    => $subject,
                );

        # Perform BLAST call
        $fac->blastn(   -query          => $CRPfile,
                        -outfile        => $outFile,
                        -method_args    => [ -word_size => 7],
                    );
```

**No HTML Output**
```
# Create StandAloneBlastPlus Factory
        my $fac = Bio::Tools::Run::StandAloneBlastPlus->new(
                    -db_data    => $subject,
                );

        # Perform BLAST call
        $fac->blastn(   -query          => $CRPfile,
                        -outfile        => $outFile,
                        -method_args    => [ -word_size => 7, html => ''],
                    );
```

**HTML Output, but no results stored in object when `while ( my $result = $fac->next_result ) { ... }`**
```
# Create StandAloneBlastPlus Factory
        my $fac = Bio::Tools::Run::StandAloneBlastPlus->new(
                    -db_data    => $subject,
                );

        # Perform BLAST call
        $fac->blastn(   -query          => $CRPfile,
                        -outfile        => $outFile,
                        -method_args    => [ -word_size => 7, html => ' '],
                    );
```

**Comment by bosborne** [comment]
Andres,

It’s not clear what you are asking for. You’ve written that you can get HTML output, which is useful if you wanted to create Web pages, for example.

But then you’re attempting to parse HTML using SearchIO, and that won’t work, it’s not a supported format.

What is it that you are trying to do?

Brian O.

**Comment by bosborne** [comment]
Your example works for me:

use Bio::Tools::Run::StandAloneBlastPlus;

# Create StandAloneBlastPlus Factory
my $fac
    = Bio::Tools::Run::StandAloneBlastPlus->new( -db_data => 'test1.fa', );

# Perform BLAST call
$fac->blastn(
    -query       => 'test1.fa',
    -outfile     => 'test.html',
    -method_args => [ -word_size => 7, html => '' ],
);

However, as mentioned, you can not parse HTML output with SearchIO.

**Comment by bretonics** [comment]
AH, I see what happens then. I thought I was calling the HTML output incorrectly somehow.

Thanks Brian.
