### ISSUE TITLE
qualifiers for for water/needle@ Bio::Factory::EMBOSS

### ISSUE THREAD

**Issue by rafalcode** [bioperl/bioperl-run#50]
The latest docs for this module refer to "-asequence" and "-seqall" for these two tools,  the latter seems to be rejected. I'm on Debian Testing (Stretch) which has EMBOSS 6.6.0. I found using EMBOSS actual docs that "-sequencea" and "-sequenceb" work instead.

**Comment by rafalcode** [comment]
Sorry error: non-working is "-sequencea" and "-seqall".
Working is "-asequence and "-bsequence"

**Comment by rafalcode** [comment]
yes, exactly. that's the one that works. perl hash keys matching the EMBOSS options exactly.

**Comment by bosborne** [comment]
Done.

**Comment by rafalcode** [comment]
cheers, thanks.
